version: '2'
services:
    salefutbolautomator-app:
        image: salefutbolautomator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://salefutbolautomator-mysql:3306/salefutbolautomator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    salefutbolautomator-mysql:
        extends:
            file: mysql.yml
            service: salefutbolautomator-mysql
